---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dns-resolver.fullname" . }}-registrypullsecret
  labels:
    {{- include "dns-resolver.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
